### PR TITLE
Support +srv mongo connections

### PR DESCRIPTION
**Pull request by markitosgv**
Allow using mongodb+srv connection

### CODE REVIEW

**Review by beniamin — APPROVED** [review]

**Review by iosifch — APPROVED** [review]

**Review by iosifch — CHANGES_REQUESTED** [review]
Thank you for this pull request. I think you should provide some tests for this change.

**Comment by markitosgv** [comment]
@iosifch added a transport new assert

**Review by iosifch — APPROVED** [review]

**Comment by markitosgv** [comment]
Could you please merge and do a new minor release? Thanks @iosifch

**Comment by iosifch** [comment]
Sure! I'll do this immediately!

**Comment by iosifch** [comment]
Check it out, there's one new version - 0.1.1. Thanks for your contribution!

**Pull request merged**
